# Use Clojure in JupterLite

## 1. Basic Data Types and Operations

### Numbers

In [6]:
42          ; integer
3.14        ; floating point

3.14

In [5]:
22/7

3.142857142857143

### Strings

In [8]:
"Hello"     ; string
str         ; string function
(str "Hello" " " "World")  ; => "Hello World"

Hello World

### Keywords

In [9]:
:name       ; keyword
:user/name  ; namespaced keyword

:user/name

### Symbols

In [11]:
(def x 42)  ; define variable
(def greeting "Hello")

#'user/greeting

### Basic Operations

In [12]:
(+ 1 2 3)   ; => 6
(- 10 5)    ; => 5
(* 4 3)     ; => 12
(/ 10 2)    ; => 5

5

## 2. Collection Types

### Lists

In [16]:
'(1 2 3)    ; quoted list
(list 1 2 3); create list
(first '(1 2 3))      ; => 1
(rest '(1 2 3))       ; => (2 3)

(2 3)

### Vectors

In [17]:
[1 2 3]     ; vector
(vector 1 2 3)
(get [1 2 3] 0)       ; => 1
(nth [1 2 3] 1)       ; => 2

2

### Maps

In [19]:
{:name "John" :age 30}
(hash-map :name "John" :age 30)
(get {:name "John" :age 30} :name)  ; => "John"
(:name {:name "John" :age 30})      ; => "John"

John

### Set

In [20]:
#{1 2 3}    ; set
(hash-set 1 2 3)
(contains? #{1 2 3} 1)  ; => true

true

## 3. Function Definition and Usage

### Function Definition

In [28]:
(fn [x] (* x x))              ; anonymous function
(def square (fn [x] (* x x))) ; named function
(defn square [x] (* x x))     ; shorthand form

(square 5)        ; => 25

25

### Multiple Parameters

In [30]:
(defn greet
  [name]
  (str "Hello, " name "!"))

(greet "Alice")   ; => "Hello, Alice!"

Hello, Alice!

In [31]:
(defn add-numbers
  [x y]
  (+ x y))

#'user/add-numbers

### Variable Arguments

In [32]:
(defn sum
  [& numbers]
  (apply + numbers))

(sum 1 2 3 4)

10

## 4. Control Flow:

### if expression

In [34]:
;; if expression
(if (> 5 3)
  "5 is greater than 3"
  "5 is not greater than 3")

5 is greater than 3

### when (only true branch)

In [35]:
(when (> 5 3)
  (js/console.log "5 is greater than 3")
  "5 is greater")

5 is greater

### cond (multiple conditions)

In [36]:
(cond
  (< x 0) "negative"
  (> x 0) "positive"
  :else "zero")

positive

### case (pattern matching)

In [37]:
(case x
  5 "x is 5"
  10 "x is 10"
  "x is something else")

x is something else

## 5.Sequence Operations

### map

In [39]:
(map inc [1 2 3])          ; => (2 3 4)
(map #(* % 2) [1 2 3])     ; => (2 4 6)

(2 4 6)

### filter

In [40]:
(filter even? [1 2 3 4])   ; => (2 4)
(filter #(> % 2) [1 2 3 4]); => (3 4)

(3 4)

### reduce

In [41]:
(reduce + [1 2 3 4])       ; => 10
(reduce str ["a" "b" "c"]) ; => "abc"

abc

### composition

In [42]:
(def times2-plus10 (comp #(+ % 10) #(* % 2)))
(times2-plus10 5)          ; => 20

20

## 6. Destructuring

### Vector destructuring

In [44]:
(def points [[1 2] [3 4] [5 6]])
(let [[x y] [1 2]]
  (+ x y))  ; => 3

3

### Map destructuring

In [45]:
(let [{name :name age :age} {:name "John" :age 30}]
  (str name " is " age))  ; => "John is 30"

John is 30

### Using :keys shorthand

In [46]:
(let [{:keys [name age]} {:name "John" :age 30}]
  (str name " is " age))  ; => "John is 30"

John is 30

### Nested destructuring

In [47]:
(let [{:keys [name address]} {:name "John" 
                             :address {:street "123 Main St" 
                                     :city "Boston"}}
      {:keys [street city]} address]
  [name street city])  ; => ["John" "123 Main St" "Boston"]

["John" "123 Main St" "Boston"]

## 7. Atoms and State Management

### Creating and using atoms

In [49]:
(def counter (atom 0))
(deref counter)      ; => 0
@counter             ; => 0 (shorthand for deref)

0

### Updating atoms

In [50]:
(swap! counter inc)  ; => 1
(swap! counter + 5)  ; => 6

6

### Reset atom value

In [51]:
(reset! counter 0)   ; => 0

0

### Watching for changes

In [52]:
(add-watch counter :watcher
  (fn [key atom old-state new-state]
    (js/console.log "Counter changed from" old-state "to" new-state)))

[object Object]

In [53]:
(swap! counter + 5)  ; => 6

5

## 8. Higher-order Functions

### Function that returns a function

In [55]:
(defn multiplier [x]
  (fn [y] (* x y)))

(def times-two (multiplier 2))
(times-two 4)  ; => 8

8

### Function composition with threading macros

In [56]:
(-> 5
    (* 2)
    (+ 3)
    (/ 2))  ; => 6.5

6.5

### Thread-last macro

In [57]:
(->> [1 2 3 4]
     (map #(* % 2))
     (filter even?)
     (reduce +))  ; => 20

20

### Partial application

In [58]:
(def add-five (partial + 5))
(add-five 3)  ; => 8

8

## 9. Working with JavaScript Interop

### Calling JavaScript methods

In [60]:
(js/console.log "Hello from ClojureScript!")
(js/parseInt "42")
(js/Math.random)

0.03118632507468555

### Working with JavaScript objects

In [61]:
(def obj (js-obj "name" "John" "age" 30))
(.-name obj)  ; => "John"
(set! (.-name obj) "Jane")

undefined

### Converting between Clojure and JavaScript

In [62]:
(clj->js {:name "John" :age 30})  ; => JavaScript object
(js->clj #js {:name "John" :age 30}) ; => Clojure map

{"name" "John", "age" 30}

### Using JavaScript array methods

In [63]:
(def arr #js [1 2 3])
(.push arr 4)
(.join arr ",")  ; => "1,2,3,4"

1,2,3,4

## 10. Regular Expressions and String Operations

### Regular expressions

In [67]:
(def email-regex #"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}")
(re-matches email-regex "user@example.com")  ; => "user@example.com"
(re-find #"\d+" "abc123def")  ; => "123"

123

### String operations

In [69]:
(clojure.string/split "a,b,c" #",")  ; => ["a" "b" "c"]
(clojure.string/join ", " [1 2 3])   ; => "1, 2, 3"
(clojure.string/replace "hello world" #"o" "0")  ; => "hell0 w0rld"
(clojure.string/upper-case "hello")  ; => "HELLO"

HELLO

## 11. Lazy Sequences and Range

### Creating sequences

In [71]:
(range 5)        ; => (0 1 2 3 4)
(range 2 5)      ; => (2 3 4)
(range 0 10 2)   ; => (0 2 4 6 8)

(0 2 4 6 8)

### Sequence operations

In [72]:
(take 3 (range))      ; => (0 1 2)
(drop 2 [1 2 3 4 5])  ; => (3 4 5)
(take-while #(< % 4) (range))  ; => (0 1 2 3)
(drop-while #(< % 4) (range 10))  ; => (4 5 6 7 8 9)

(4 5 6 7 8 9)

## 12. Logic Operations and Set Operations

### Logic operations

In [74]:
(and true false)     ; => false
(or false nil true)  ; => true
(not true)           ; => false
(if-not false :yes)  ; => :yes

:yes

### Set operations

In [76]:
(def set1 #{1 2 3})
(def set2 #{2 3 4})
(clojure.set/union set1 set2)         ; => #{1 2 3 4}
(clojure.set/intersection set1 set2)   ; => #{2 3}
(clojure.set/difference set1 set2)     ; => #{1}

#{1}

## 13. More Collection Operations

### Into - Adding elements to collections

In [79]:
(into [] '(1 2 3))        ; => [1 2 3]
(into {} [[:a 1] [:b 2]]) ; => {:a 1 :b 2}

{:a 1, :b 2}

### Updating nested structures

In [80]:
(update-in {:user {:age 30}} [:user :age] inc)  ; => {:user {:age 31}}
(assoc-in {} [:user :name] "John")             ; => {:user {:name "John"}}

{:user {:name "John"}}

### Sequence transformations

In [81]:
(partition 2 [1 2 3 4 5 6])     ; => ((1 2) (3 4) (5 6))
(interleave [:a :b :c] [1 2 3]) ; => (:a 1 :b 2 :c 3)
(interpose "," ["a" "b" "c"])   ; => ("a" "," "b" "," "c")

("a" "," "b" "," "c")

## 14. Conditionals and Pattern Matching

###  Some and every?

In [84]:
(some even? [1 2 3 4])     ; => true
(every? odd? [1 3 5 7])    ; => true

true

### Conditional execution

In [85]:
(when-let [x (first [1 2 3])]
  (+ x 10))                ; => 11

11

In [86]:
(if-let [x (first [])]
  (+ x 10)
  "empty")                 ; => "empty"

empty

### Multiple value binding

In [87]:
(when-let [[x y] [1 2]]
  (+ x y))                 ; => 3

3

## 15.  Math and Number Operations

### Math operations

In [89]:
(max 1 2 3 4)              ; => 4
(min 1 2 3 4)              ; => 1
(Math/abs -5)              ; => 5
(Math/round 3.7)           ; => 4

4

### Number predicates

In [90]:
(pos? 5)                   ; => true
(neg? -3)                  ; => true
(zero? 0)                  ; => true
(even? 4)                  ; => true
(odd? 3)                   ; => true

true

## 16. Working with Date and Time

### Creating dates

In [97]:
(js/Date.)                    ; Current date
(js/Date. "2024-01-01")      ; Specific date
(.getTime (js/Date.))       ; Timestamp

1732439226051

### Date operations

In [98]:
(def date (js/Date.))
(.toISOString date)                 ; ISO string format
(.toLocaleDateString date)          ; Local date string
(.getFullYear date)                 ; Get year
(.getMonth date)                    ; Get month (0-11)

10

### More date operations

In [99]:
(.getDate date)                     ; Get day of month
(.getDay date)                      ; Get day of week (0-6)
(.getHours date)                    ; Get hours
(.getMinutes date)                  ; Get minutes
(.getSeconds date)                  ; Get seconds

49

### Date formatting

In [102]:
(.toDateString date)

Sun Nov 24 2024

In [101]:
(.toTimeString date)

17:07:49 GMT+0800 (China Standard Time)

## 17. JSON Operations

### Parse JSON string

In [105]:
(js/JSON.parse "{\"name\": \"John\"}")

[object Object]

### Convert to JSON string

In [106]:
(js/JSON.stringify (clj->js {:name "John"}))

{"name":"John"}

### Working with JSON data

In [107]:
(-> "{\"name\": \"John\", \"age\": 30}"
    js/JSON.parse
    js->clj
    (get "name"))  ; => "John"

John

## 18. Function Composition Patterns

### Juxt - multiple functions on same input

In [109]:
(def stats (juxt count first last))
(stats [1 2 3 4 5])  ; => [5 1 5]

[5 1 5]

### Complement - opposite of a predicate

In [110]:
(def not-empty? (complement empty?))
(not-empty? [1 2 3])  ; => true

true

### Fnil - provide default for nil

In [111]:
(def safe-inc (fnil inc 0))
(safe-inc nil)  ; => 1
(safe-inc 1)    ; => 2

2

## 19. Error Handling

### Try-catch in ClojureScript

In [112]:
(try
  (/ 1 0)
  (catch js/Error e
    (js/console.error "Error:" (.-message e)))
  (finally
    (js/console.log "Cleanup")))

Infinity

### Custom error handling

In [113]:
(defn safe-divide [x y]
  (try
    (/ x y)
    (catch js/Error _
      :division-error)))

#'user/safe-divide

## 20. Working with Sequences

### Infinite sequences

In [114]:
(def integers (iterate inc 0))
(take 5 integers)  ; => (0 1 2 3 4)

(0 1 2 3 4)

### Sequence transformations

In [116]:
(partition-by #(< % 3) [1 2 3 2 1 4 5])  ; => ((1 2) (3) (2 1) (4 5))
(partition-all 2 [1 2 3 4 5])            ; => ((1 2) (3 4) (5))
(frequencies ["a" "b" "a" "c"])          ; => {"a" 2, "b" 1, "c" 1}

{"a" 2, "b" 1, "c" 1}

### Sequence combinations

In [117]:
(for [x [1 2]
      y [3 4]]
  [x y])

([1 3] [1 4] [2 3] [2 4])

## 21. Memoization and Caching

### Basic memoization

In [119]:
(def memo-fn
  (memoize (fn [x]
             (js/console.log "Computing for" x)
             (* x x))))

#'user/memo-fn

In [122]:
(memo-fn 5)  ; Computes and caches

25

In [123]:
(memo-fn 5)  ; Returns cached result

25

## 22.  Working with Volatile!

### Using volatile! for local state

In [125]:
(def state (volatile! 0))
(vreset! state 1)        ; Set value
(vswap! state inc)       ; Update value
@state                   ; Get value

2

### Performance critical loops

In [126]:
(let [v (volatile! 0)]
  (dotimes [_ 10]
    (vswap! v + 2))
  @v)

20

## 23. Loop and Recur

In [127]:
;; Basic recursion
(loop [x 10
       acc []]
  (if (zero? x)
    acc
    (recur (dec x) (conj acc x))))  ; => [10 9 8 7 6 5 4 3 2 1]

;; Factorial with loop/recur
(defn factorial [n]
  (loop [n n
         acc 1]
    (if (= n 0)
      acc
      (recur (dec n) (* acc n)))))

#'user/factorial

### Basic recursion

In [128]:
(loop [x 10
       acc []]
  (if (zero? x)
    acc
    (recur (dec x) (conj acc x))))  ; => [10 9 8 7 6 5 4 3 2 1]

[10 9 8 7 6 5 4 3 2 1]

### Factorial with loop/recur

In [130]:
(defn factorial [n]
  (loop [n n
         acc 1]
    (if (= n 0)
      acc
      (recur (dec n) (* acc n)))))

#'user/factorial

In [131]:
(factorial 10)

3628800

## 24.  Conditional Threading Macros

### some->

In [137]:
;; some-> (thread-first with nil short-circuiting)
;; Returns nil if any step returns nil, otherwise threads value through

(some-> {:a {:b {:c 1}}}
        :a
        :b
        :c
        inc)  ; => 2

(some-> {:a nil}
        :a
        :b
        inc)  ; => nil

null

###  some->>

In [136]:
;; (thread-last with nil short-circuiting)
;; Similar to some->, but inserts value as last argument
(some->> [1 2 3 4]
         (map inc)
         (filter even?)
         (reduce +))  ; => 10

(some->> []
         (map inc)
         (filter even?)
         first)  ; => nil

null

### cond-> 

In [140]:
;; cond-> (conditional thread-first)
;; Performs transformations only when the condition is true
(cond-> 5
        true inc                ; always applies
        (> 5 3) (* 2)          ; applies when 5 > 3
        false dec              ; never applies
        (= 5 10) (* 3))       ; doesn't apply

12

### cond->>

In [142]:
;; cond->> (conditional thread-last)
;; Like cond->, but threads values as last argument
(cond->> [1 2 3 4]
         true (map inc)                    ; always applies
         (> (count [1 2]) 1) (filter odd?) ; applies when condition is true
         false (map str))                  ; never applies

(3 5)

### Practical examples

In [143]:
;; Example 1: Processing user data
(defn process-user [user]
  (cond-> user
          (:name user) (update :name clojure.string/trim)
          (:age user) (update :age #(max 0 %))
          (nil? (:active user)) (assoc :active true)))

#'user/process-user

In [144]:
;; Example 2: API response processing
(defn process-response [response]
  (some-> response
          :body
          :data
          :items
          first
          :id))

#'user/process-response

In [145]:
;; Example 3: Number processing pipeline
(defn process-number [n]
  (cond->> n
           (number? n) (+ 5)
           (> n 10) (* 2)
           (even? n) (/ 2)))

#'user/process-number

In [146]:
;; Example 4: Collection processing
(defn process-collection [coll]
  (some->> coll
           (remove nil?)
           (map inc)
           (filter even?)
           not-empty))  ; returns nil if result is empty

#'user/process-collection

In [147]:
;; Example 5: Complex data transformation
(defn transform-data [data]
  (cond-> data
          (:numbers data) (update :numbers #(map inc %))
          (:text data) (update :text clojure.string/upper-case)
          (:valid? data) (assoc :processed true)
          (:items data) (update :items #(filter some? %))))

#'user/transform-data